id: 5474d2f518fa4677baf28e4db87a1ed3
initial_creation_type: ocr
source_metadata:
  volumes:
    e11cee61c2f6492b94f02996819cfeba:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
